Repository KakaoONna/ONnaBack, pull requests merged in 2023-09, with the labels that each got.

#38 feat: 필터링 api 리턴값에 로컬스탑/관광명소 추가
  src/main/java/com/onna/onnaback/domain/place/adapter/in/web/response/PlaceReloadDto.java
  src/main/java/com/onna/onnaback/domain/place/adapter/out/persistence/PlacePersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/place/application/port/out/LoadPlacePort.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/SparkResponse.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/out/LoadSparkPort.java
  src/main/java/com/onna/onnaback/domain/spark/application/service/SparkService.java
Labels: feat

#42 refactor : 장소 상세정보 조회 API 분리
  src/main/java/com/onna/onnaback/domain/place/adapter/in/web/PlaceController.java
  src/main/java/com/onna/onnaback/domain/place/adapter/in/web/response/PlaceDetailInfo.java
  src/main/java/com/onna/onnaback/domain/place/adapter/in/web/response/PlaceResponse.java
  src/main/java/com/onna/onnaback/domain/place/application/port/in/PlaceUseCase.java
  src/main/java/com/onna/onnaback/domain/place/application/service/PlaceService.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/SparkController.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/ParticipateMemberDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/SparkListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/SparkResponse.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkRepository.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/out/LoadSparkPort.java
  src/main/java/com/onna/onnaback/domain/spark/domain/Spark.java
Labels: fix

#43 feat : 스파크 상세조회
  src/main/java/com/onna/onnaback/domain/place/adapter/in/web/PlaceController.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/SparkController.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/SparkResponse.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/in/SparkUseCase.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/out/LoadSparkPort.java
  src/main/java/com/onna/onnaback/domain/spark/application/service/SparkService.java
Labels: feat

#44 feat: 주최내역-신청목록 조회, 수락/거절 api 구현
  src/main/java/com/onna/onnaback/domain/apply/adapter/in/web/ApplyController.java
  src/main/java/com/onna/onnaback/domain/apply/adapter/in/web/request/ApplyProcessRequest.java
  src/main/java/com/onna/onnaback/domain/apply/adapter/in/web/request/ApplyRequest.java
  src/main/java/com/onna/onnaback/domain/apply/adapter/out/persistence/ApplyPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/apply/adapter/out/persistence/ApplyRepository.java
  src/main/java/com/onna/onnaback/domain/apply/application/port/in/ApplyUseCase.java
  src/main/java/com/onna/onnaback/domain/apply/application/port/out/LoadApplyPort.java
  src/main/java/com/onna/onnaback/domain/apply/application/port/out/SaveApplyPort.java
  src/main/java/com/onna/onnaback/domain/apply/application/service/ApplyService.java
  src/main/java/com/onna/onnaback/domain/apply/domain/MemberSparkMapping.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/SparkController.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/HostListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/SparkApplyListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/in/SparkUseCase.java
  src/main/java/com/onna/onnaback/domain/spark/application/service/SparkService.java
Labels: feat, refactor

#47 feat: spark 엔티티에 상시 항목 추가
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/request/HostDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/HostListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/domain/Always.java
  src/main/java/com/onna/onnaback/domain/spark/domain/Spark.java
Labels: feat

#49 feat: 주최내역 초기화면 N명 신청대기 기능 구현
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/HostListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
Labels: feat

#50 feat: 주최 api capacityType 추가
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/request/HostDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/HostListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/domain/CapacityType.java
  src/main/java/com/onna/onnaback/domain/spark/domain/Spark.java
Labels: feat

#52 feat: 신청 관련 에러 처리 구현
  src/main/java/com/onna/onnaback/domain/apply/adapter/out/persistence/ApplyPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/apply/application/port/out/LoadApplyPort.java
  src/main/java/com/onna/onnaback/domain/apply/application/port/out/SaveApplyPort.java
  src/main/java/com/onna/onnaback/domain/apply/application/service/ApplyService.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/in/SparkUseCase.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/out/LoadSparkPort.java
  src/main/java/com/onna/onnaback/domain/spark/application/service/SparkService.java
  src/main/java/com/onna/onnaback/domain/spark/domain/Spark.java
  src/main/java/com/onna/onnaback/global/exception/ErrorCode.java
Labels: feat

#53 feat: 주최/신청 내역에 img 추가
  src/main/java/com/onna/onnaback/domain/apply/adapter/in/web/response/ApplyDto.java
  src/main/java/com/onna/onnaback/domain/apply/adapter/out/persistence/ApplyPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/SparkController.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/request/HostDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/HostListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
  src/main/java/com/onna/onnaback/domain/spark/application/port/in/SparkUseCase.java
  src/main/java/com/onna/onnaback/domain/spark/application/service/SparkService.java
Labels: feat

#56 feat: spark getList place name 추가
  src/main/java/com/onna/onnaback/domain/spark/adapter/in/web/response/SparkListDto.java
  src/main/java/com/onna/onnaback/domain/spark/adapter/out/persistence/SparkPersistenceAdapter.java
Labels: feat

#57 feat: spark getList memberId 제거
  src/main/java/com/onna/onnaback/domain/apply/adapter/in/web/ApplyController.java
  src/main/java/com/onna/onnaback/domain/apply/application/port/in/ApplyUseCase.java
  src/main/java/com/onna/onnaback/domain/apply/application/service/ApplyService.java
Labels: feat
